---
title: "visualization1"
author: "Rebecca Shyu"
date: "2024-09-26"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
remotes::install_github("ropensci/rnoaa")
library(patchwork)
library(haven)
```

## R Markdown


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = floor_date(date, unit="month")) |>
  select(name, id, everything())
```
Let's make some plots

```{r}
weather_df %>% 
  ggplot(aes(x= prcp)) +
  geom_histogram()
```

```{r}
weather_df %>% 
  filter(tmax > 20, tmax < 30) %>% 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) +
  geom_point()
```
## group_by()

```{r}
weather_df %>% 
  group_by(name)
```

counting stuff

```{r}
weather_df %>% 
  group_by(name) %>% 
  summarize(
    n_obs = n(),
    n_dist = n_distinct(month))

weather_df %>% 
  count(name)
```

```{r}
weather_df %>% 
  drop_na(tmax) %>% 
  filter(name != "Molokai_HI") %>% 
  mutate(
    cold = case_when(
      tmax <5 ~ "cold",
      tmax >=5 ~ "not_cold"
    )
  ) %>% 
  group_by(name, cold) %>% 
  summarise(count = n()) 



weather_df %>% 
  drop_na(tmax) %>% 
  filter(name != "Molokai_HI") %>% 
  mutate(
    cold = case_when(
      tmax <5 ~ "cold",
      tmax >=5 ~ "not_cold"
    )
  ) %>% 
  janitor::tabyl(name, cold)
```


## general numeric summaries

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarise(
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_tmin = median(tmin, na.rm= TRUE),
    sd_prcp = sd(prcp, na.rm=TRUE)
  ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
```

format for readers

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarise(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) %>% 
  knitr::kable(
    digits = 3,
    col.names = c("Month", "Central Park", "Molokai", "Waterhole")
    )
```



